level2/gibi/config/routes.rb
Rails.application.routes.draw do
  get 'conversions/new'
 
  root 'conversions#new'
  resources :conversions
end

level2/gibi/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

level2/gibi/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

level2/gibi/app/controllers/conversions_controller.rb
require_relative '../../../../level1/shadok'
class ConversionsController < ApplicationController
  # Render form to create a request
  def new
  end

  # Render response on a conversion to shadok number
  def create
    value = Integer(conversion_params) rescue nil
    if !value.is_a? Integer
      render plain: params[:number].merge({error: 'not a number'}).to_json,
        status: :bad_request
      return
    end
    render plain: params[:number].merge({shadok: value.shadok}).to_json
  end

  private
  def conversion_params
    params.require(:number).require(:value)
  end
end

level2/gibi/app/helpers/application_helper.rb
module ApplicationHelper
end

level2/gibi/app/helpers/conversions_helper.rb
module ConversionsHelper
end

level2/gibi/app/views/conversions/new.html.erb
<h1>New conversion</h1>
<%= form_with scope: :number, url: conversions_path, local: true do |form| %>
  <p>
    <%= form.label :value %><br>
    <%= form.text_field :value %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

level2/gibi/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gibi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>